### ISSUE TITLE
Template for Zabbix 3.4.8

### ISSUE THREAD

**Issue by perrfect** [ronivay/zabbix-dell-omsa#1]
Hello.
Can i use your template for my Zabbix 3.4.8? And what should i change in the template for this version Zabbix?
Thank you.

**Comment by ronivay** [comment]
Sorry, i have missed this entirely somehow. You’ve probably already solved this but anyway. Templates aren’t usually fully backwards compatible between major releases. Most likely you can use most of it, but needs tweaking. Unfortunately i don’t currently run any 3.x version of zabbix so can’t give a detailed guide. Feel free to create a pull request if you ended up to a working template and would like to share it with others.
